### ISSUE TITLE
Домашка №0, которую и так все сделали

### ISSUE THREAD

**Issue by tiny-kottan** [aerobium/kottans-JS-2016#2]
1. Установить git / ознакомиться с ним
2. IDE/editor, ознакомиться с ним.
3. DevTools - пройти на CodeSchool (http://discover-devtools.codeschool.com/).
4. Github - завести репозитарий для домашек.
5. GitBranching: http://pcottle.github.io/learnGitBranching/ пройти Main, забросить скриншот в гитхаб, сюда запостить ссылку

**Comment by aerobium** [comment]
[https://github.com/aerobium/kottans-JS-2016/blob/master/week01/git-tutorial.jpg](url)

**Comment by sudodoki** [comment]
Wrong link here. LGTM though

**Comment by aerobium** [comment]
fixed it - [picture](https://raw.githubusercontent.com/aerobium/kottans-JS-2016/master/week01/git-tutorial.jpg)
